apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: discovery-server
  type: ClusterIP
