apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-mysql-pv
  labels:
    type: keycloak-db
spec:
  storageClassName: keycloak-manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql_keycloak_data"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pvc
spec:
  storageClassName: keycloak-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: keycloak-db
