apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  selector:
    app: keycloak-mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
