apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  mysql-root-password: root
  mysql-user: user
  mysql-password: user
