apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
  - port: 9003
    targetPort: 9003
    name: http
  - port: 50053
    targetPort: 50053
    name: grpc
  selector:
    app: order-service
  type: ClusterIP
