apiVersion: v1
kind: Service
metadata:
  name: order-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
  - port: 8007
    targetPort: 8007
    name: http
  - port: 50053
    targetPort: 50053
    name: grpc
  selector:
    app: order-service
  type: ClusterIP
